kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv0005
  namespace: nexus
  labels:
    type: local
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/data/pv0005"
