apiVersion: networking.k8s.io/v1beta1 # for versions before 1.14 use extensions/v1beta1
kind: Ingress
metadata:
  name: nexus-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: nexus.local
    http:
      paths:
      - path: /
        backend:
          serviceName: sonatype-nexus-1585941622
          servicePort: 8080
